development:
    dialect: postgres
    datasource: host=localhost dbname=test-go user=api password=api
    dir: migrations
    table: migrations
production:
    dialect: postgres
    datasource: host=prodhost dbname=proddb user=${DB_USER} password=${DB_PASSWORD} sslmode=required
    dir: migrations
    table: migrations
